import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";



const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "AI Course ",
    description: "Modern AI Course Generated By Yourself And Powered by AI",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black-100 text-white`}
        >

        {children}

        </body>
        </html>
    );
}
